<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'VHDUserAuth\Module'                        => __DIR__ . '/Module.php',
    'VHDUserAuth\Controller\VHDUserAuthController' => __DIR__ . '/src/VHDUserAuth/Controller/VHDUserAuthController.php',
    'VHDUserAuthTest\Framework\TestCase'        => __DIR__ . '/tests/VHDUserAuth/Framework/TestCase.php',
    'VHDUserAuthTest\SampleTest'                => __DIR__ . '/tests/VHDUserAuth/SampleTest.php',
);
