 <?php  
        $this->headScript()->appendFile($this->basePath() . '/js/user/script.js'); 
        $this->headLink()->prependStylesheet($this->basePath() . '/css/user/style.css');
        
        $title = 'Tạo tài khoản mới';
        $this->headTitle($title);
       
        
 ?>
 <div id="divAdd">
<?php 


 ?>
 
 <div class="row">
   <div class="span3">
     <h4><?php echo $this->escapeHtml($title);?></h4>
     <form name="userAddForm" id="userAddForm" method="post" 
                action="<?php echo $this->url('user',array('action'=> 'add'));?>">
        
         <label for="usertype" >Loại tài khoản</label>
         <select name="usertype">
            <option value="0">Khách hàng</option>
            <option value="1" <?php echo $this->user->usertype==1?'selected':'' ;?>>Admin</option>
         </select>
        <label for="username" >Tên đăng nhập(*)</label>
        <input type="text" name="username" id="username"                  
                value="<?php echo $this->user->username;?>" maxlength="30"/>
        <label for="password" >Mật khẩu (*)</label>
        <input type="text" name="password" id="password" 
                 value="<?php echo $this->user->password;?>" 
                maxlength="30"/> 
        
              
       <div id="errormsg"> <?php echo $errmsg;?></div>
        <hr/>
        
        <label for="submitbutton"></label>
        <input type="submit" name="submitbuttom" id="submitbutton" value=" Thêm " />
     </form>
   </div>
   <div class="span7">
         <form action ="<?php echo $this->url('user', array('action'=>'index'));?>" 
                name="customerForm"
                method="post" id="customerForm">
            <div id="customerList">
            <input type="hidden" name="page" id="page" value="<?php echo $page; ?>" />            
            <table class="table">
            <thead>
               <tr>
                    <th width="25px">#</th>
                    <th width="55px">Nick</th>   
                    <th>Mật khẩu</th>                   
                    <th>Mã TK</th>
                    <th>Tài khoản</th>
                    <th>Ngày tạo</th>      
                    <th>Loại TK</th>                       
               </tr>            
            </thead>
            <tbody>
                <?php $i = ($page -1)* $row + 1 ;?>
                <?php foreach($paginator as $item):?>
               <tr>
                    <td><?php echo $i++; ?></td>
                    <td style="text-align:center;">
                       <?php echo $item->getNick();?>
                    </td>
                    <td><?php echo $item->getPassword(); ?></td>
                    <td><?php echo $item->getBalance_id();?></td> 
                     <td><?php echo $item->getAmount();?></td> 
                    <td><?php echo $item->getDatecreated();?></td>                   
                    <td>Khách hàng</td>
               </tr>
               <?php endforeach;?>
            </tbody>
            <tfoot>
                <tr>
                            <td colspan="7">
                                 <?php    
                                    $url = $this->url('user', array('action'=>'index'));
                                            echo $this->paginationControl(
                                                        $paginator, 'Sliding', 'paginator-slide', 
                                                        array('url'=>$url)
                                    );
                                ?>   
                            </td>
                           </tr>
            </tfoot>
            </table>
 
        </div> 
       </form>
   </div>
    
    
</div>
</div>