<?php if (!$this->isAjaxRequest):?>
<?php  
        $this->headScript()->appendFile($this->basePath() . '/js/admin/additionalfee.js'); 
        $this->headScript()->appendFile($this->basePath() . '/js/jquery.autosize.min.js');
        $this->headScript()->appendFile($this->basePath() . '/js/jshashtable-3.0.js');
        $this->headScript()->appendFile($this->basePath() . '/js/jquery.numberformatter-1.2.3.js');
          
        $this->headScript()->appendFile($this->basePath() . '/js/jquery.mousewheel.pack.js');
        
        
        
        
        $this->headLink()->prependStylesheet($this->basePath() . '/css/admin/additionalfee.css');

 
    
        
        
        $title = 'Nhập Tổng chi phí';
        $this->headTitle($title);
       
   
 ?>
 
<div class="span11">
	<form name="frmShipment" id="frmShipment" method="post"
		action="<?php echo $this->url('admin',array('action'=>'additionalfee'));?>">
		 
		 <h3>Nhập tổng chi phí</h3>
		 <div id="divShipemnts">
		      Shipment: 
		      <select name="shipment_id" id="shipment_id">
		          <option></option>
		          <?php foreach($this->shipments as $item):?>
		          <option value="<?php echo $item->getId();?>" <?php echo $item->getId()==$this->shipment_id?"selected":""; ?> ><?php echo $item->getShip_name();?></option>
		          <?php endforeach;?>
		      </select>		      
		      <input type="hidden" name="hidden_shipment_id" id="hidden_shipment_id" value="<?php echo $this->shipment_id;?>" />
		      <input type="submit" name="btnShow" value="Submit" class="btn" />	      
		 </div>
		
		<hr/>
<?php endif;?>
	<?php if ($this->shipment_id):?>	
	  <?php if (!$this->isAjaxRequest):?>
		
		<table>
			     <tr>
			         <td>
			            <input type="hidden" name="id" id="ship_id" value="<?php echo $this->shipment_id;?>" />
				       	<label for="ship_date">Date</label>
				       	<input type="text" name="ship_date" id="ship_date" class="datepicker" />
			         </td>			         
			         <td><label for="total">Total (USD)</label><input type="text" name="total" value="" id="total"/></td>
			         
			     </tr>
				 
				 <tr>
				    <td colspan="2">
				        <label for="note">Note</label> <textarea name="note" id="note" ></textarea>
				    </td>
				 </tr>
				 <tr>
				    <td colspan="2">
				        <input type="button" id="btnSave" class="btn" name="btnSave" value="Save" />
				    </td>
				 </tr>
			 	 
	     </table>
	     
	     <hr/>	
		
		<div id="divShippingFeeList">
		
		 
      <?php endif;?>
        	 
        	 <div id="anchor"></div>        	              
            <div id="shippingWeightList">
               <div id="divTableHeader"></div>
        		<table class="table" id="shippingWeightTable">
        			<thead>
        				<tr>
        					<th style="width: 30px;"><div class="soNo">#</div></th>        					
        					<th style="width: 150px;"><div class="soNick">Admin</div></th>
        					<th style="width: 100px;"><div class="soDate">Date</div></th>
        					<th style="width: 120px;"><div class="soTotal">Total</div></th>
        					<th><div class="soNote">Note</div></th>
        					<th style="width: 50px;">-</th>
        					 
        				</tr>
        			</thead>
        			<tbody>
        			<?php  
        			     $i = 1;
        			      
        			     $total = 0;
        			      
        			 ?>
        			<?php if ($this->list):?>
        			  
        			    <?php foreach ($this->list as $item):?>
        			        <?php 
        			             
        			             $total += $item->getTotal(); 
        			         ?>
        			    	<tr class="trItem">
        			    		<td class="soNo">
        			    		  <div class="soNo">
        			    		       <?php echo $i++; ?>
        			    		  </div>          			    		  
        			    		</td>        			    		 
        			    		<td>
        			    		       <div class="soNick"><?php echo $item->getAdmin();?></div>
        			    		</td>
        			    		<td ><?php echo date("d-m-Y",strtotime($item->getDate()));?></td>        			    		
        			    		<td style="width: 100px"><div class="divTotal"><?php echo $item->getTotal()==0?"": number_format($item->getTotal(),2,".",",");?></div></td>        			    		
        			    		<td><div class="divNote"><?php echo $item->getNote();?></div></td>
        			    		<td><a class="del" href="#" data-id="<?php echo $item->getId();?>" data-url="<?php echo $this->url('admin',array('action'=>'deladditionalfee'));?>" title="Xóa bỏ" ><span class="icon-trash"></span></a> </td>
        			    		
        			    	</tr>
        			    	
        			    
        			    <?php endforeach;?>
        			<?php endif;?>
        			</tbody>
        			<tfoot> 
        			     <tr>
        			         <td colspan="3">        			             
        			         </td>
        			          
        			         <td style="text-align: right">
        			             <span class="label" id="total_final"><?php echo number_format($total,2,".",",");?></span>
        			         </td>
        			         <td>
        			         </td>
        			         <td>
        			         </td>
        			     </tr>       				 
        			     <tr>
        			         <td colspan="7">
        			              
        			          </td>  
        			            
        			          
        			     </tr>
        			</tfoot>
        		</table>           
            	</div>
         	 <?php if (!$this->isAjaxRequest):?>  
                </div>
             <?php endif;?>
          <?php endif;?>
 <?php if (!$this->isAjaxRequest):?>  
	</form>

</div>
 
<?php endif;?>


