<?php if (!$this->isAjaxRequest):?>
<?php  
        $this->headScript()->appendFile($this->basePath() . '/js/admin/admindeleteshipment.js'); 
         
        $this->headLink()->prependStylesheet($this->basePath() . '/css/admin/admindeleteshipment.css');
        
       
       // $this->headTitle('Quản lý Đợt hàng');
         
        
 ?>
 
 
   <div class="span11">
        <h4>Danh sách Đợt hàng đã hoàn thành</h4>
        <h2 class="warning">Chú ý: Dữ liệu xóa không thể phục hồi.</h2>
         <form action ="<?php echo $this->url('admin', array('action'=>'admindeleteshipment'));?>" 
                name="shipmentForm"
                method="post" id="shipmentForm">

            <div id="shipmentList">
 <?php endif;?>            
            <input type="hidden" name="page" id="page" value="<?php echo $this->page; ?>" /> 
            <input type="hidden" id="start" value="<?php echo (($this->page -1)* $this->row + 1);?>" />           
            <table class="table">
	            <thead>
	               <tr>
	                    <th>#</th>
	                    <th>Date</th>  
	                    <th>Name</th> 
	                    <th style="width: 80px; text-align: center;">Weight</th>
	                    <th>Note</th>
	                    <th>-</th>                   
	               </tr>            
	            </thead>
	            <tbody>
	                <?php $i = ($this->page -1)* $this->row + 1 ;?>
	                
	                <?php foreach($this->paginator as $item):?>
	               <tr>
	                    <td class="stt"><?php echo $i++; ?></td>
	                    <td ><a title="Xem chi tiết" href="<?php echo $this->url('admin',array('action'=>'viewshipment','id'=> $item->getId()));?>"><?php echo date('d-m-Y',strtotime($item->getShip_date()));?></a></td>
	                    <td><a title="Xem chi tiết" href="<?php echo $this->url('admin',array('action'=>'viewshipment','id'=> $item->getId()));?>"><?php echo $item->getShip_name();?></a></td> 
	                    <td style="text-align: right"><?php echo number_format($item->getWeight(),2,'.',','); ?></td>
	                    <td><?php echo $item->getNote(); ?></td>
	                    <td style="width: 50px; text-align: center;">	                                              
	                         
	                           <a class="del" title="Xóa bỏ toàn bộ dữ liệu" href="#"
	                               data-shipname="<?php echo $item->getShip_name(); ?>"
	                               data-shipmentid="<?php echo $item->getId();?>" ><span class="icon-trash"></span></a>
	                       
	                    </td>                
	               </tr>
	               <?php endforeach;?>
	            </tbody>
	            <tfoot>
	                <tr>
	                            <td colspan="9">
	                                 <?php    
	                                    $url = $this->url('admin', array('action'=>'admindeleteshipment'));
	                                            echo $this->paginationControl(
	                                                        $this->paginator, 'Sliding', 'paginator-slide', 
	                                                        array('url'=>$url,'action'=>'admindeleteshipment')
	                                    );
	                                ?>   
	                            </td>
	                           </tr>
	            </tfoot>
            </table>
 <?php if (!$this->isAjaxRequest):?>
        </div> 
       </form>
   </div>
   
   <div id="divDeleteForm">
    <span id="info" class="warning"></span>
   </div>

<?php endif;?>