<?php if (!$this->isAjaxRequest):?>
<?php  
        $this->headScript()->appendFile($this->basePath() . '/js/admin/orderlist.js'); 
         
        $this->headLink()->prependStylesheet($this->basePath() . '/css/admin/orderlist.css');
        
       
       // $this->headTitle('Quản lý Đợt hàng');
         
        
 ?>
 
 
   <div class="span11">
        <h4>Danh sách Đơn hàng</h4>
         <form action ="<?php echo $this->url('admin', array('action'=>'orderlist'));?>" 
                name="orderlistForm"
                method="post" id="orderlistForm">

             <input type="text" name="orderno" placeholder="OrderNo" id="orderno_search" value="<?php echo $this->order_search;?>" />  
             <button type="submit" class="btn"><span class='icon-search'></span></button>
                
             <hr/>
            <div id="divOrderList">
 <?php endif;?>            
            <input type="hidden" name="page" id="page" value="<?php echo $this->page; ?>" />            
            <table class="table">
	            <thead>
	               <tr>
	                    <th>#</th>
	                    <th>Date</th>  
	                    <th>OrderNo</th> 
	                    <th>Store</th>
	                    <th>Items</th>
	                    <th>Holder</th>
	                    <th>Total web</th>
	                    <th>Discount</th>
	                    <th>Total web1</th>
	                    <th>Ship US</th>
	                    <th>Tax</th>
	                    <th>Total final</th> 
	                    <th>-</th>                  
	               </tr>            
	            </thead>
	            <tbody>
	                <?php $i = ($this->page -1)* $this->row + 1 ;?>
	                <?php foreach($this->paginator as $item):?>
	               <tr>
	                    <td><?php echo $i++; ?></td>
	                    <td ><?php echo date('d-m-Y',strtotime($item->getOrderdate()));?></td>
	                    <td><a href="<?php echo $this->url('admin',array('action' => 'vieworder','id'=> $item->getOrderno()));?>" ><?php echo $item->getOrderno();?></a></td>
	                    <td><?php echo $item->getStore_name();?></td>
	                    <td><?php echo number_format($item->getItems(),0,'.',',');?></td>
	                    <td><?php echo $item->getHolder();?></td>
	                    <td><?php echo number_format($item->getTotal_web(),2,'.',',');?></td>
	                    <td><?php echo number_format($item->getDiscount(),2,'.',',');?></td>
	                    <td><?php echo number_format($item->getTotal_web1(),2,'.',',');?></td>
	                    <td><?php echo number_format($item->getShip_us(),2,'.',',');?></td>
	                    <td><?php echo number_format($item->getTax(),2,'.',',');?></td>
	                    <td><?php echo number_format($item->getTotal_final(),2,'.',',');?></td>
	                    <td style="width: 50px; text-align: center;">
	                        <a title="Sửa" href="#"><span class="icon-pencil"></span></a>
	                        &nbsp;                       
	                        <a title="Xóa" href="#"><span class="icon-trash"></span></a>
	                    </td>                
	               </tr>
	               <?php endforeach;?>
	            </tbody>
	            <tfoot>
	                <tr>
	                            <td colspan="13">
	                                 <?php    
	                                    $url = $this->url('admin', array('action'=>'orderlist'));
	                                            echo $this->paginationControl(
	                                                        $this->paginator, 'Sliding', 'paginator-slide', 
	                                                        array('url'=>$url,'action'=>'orderlist')
	                                    );
	                                ?>   
	                            </td>
	                           </tr>
	            </tfoot>
            </table>
 <?php if (!$this->isAjaxRequest):?>
        </div> 
       </form>
   </div>

<?php endif;?>