<?php  
        $this->headScript()->appendFile($this->basePath() . '/js/admin/orderfinalizing.js'); 
        
        $this->headScript()->appendFile($this->basePath() . '/js/jquery.autosize.min.js');
        $this->headScript()->appendFile($this->basePath() . '/js/jshashtable-3.0.js');
        $this->headScript()->appendFile($this->basePath() . '/js/jquery.numberformatter-1.2.3.js');
        
        $this->headScript()->appendFile($this->basePath() . '/js/jquery.mousewheel.pack.js');
        $this->headScript()->appendFile($this->basePath() . '/js/fancybox/jquery.fancybox.js');
        $this->headScript()->appendFile($this->basePath() . '/js/fancybox/jquery.fancybox-buttons.js');
        $this->headScript()->appendFile($this->basePath() . '/js/fancybox/jquery.fancybox-thumbs.js');
        
         
        $this->headLink()->prependStylesheet($this->basePath() . '/css/admin/orderfinalizing.css');
        
        $this->headLink()->prependStylesheet($this->basePath() . '/css/fancybox/jquery.fancybox.css');
        $this->headLink()->prependStylesheet($this->basePath() . '/css/fancybox/jquery.fancybox-buttons.css');
        $this->headLink()->prependStylesheet($this->basePath() . '/css/fancybox/jquery.fancybox-thumbs.css');
        
        
        $title = 'Kiểm tra lần cuối';
        $this->headTitle($title);
                 
 ?>
 
 <?php 
    
    $cards = "";
    
    foreach($this->creditcards as $item){
    	$cards .= "{creditcard:'". $item->getCreditcard()."', holder:'". $item->getHolder()."'},";
    }
    
 ?>
 <script>  
   var cards = [<?php echo $cards; ?>];
</script>

<div class="span11">
	<form name="frmShipment" id="frmShipment" method="post"
		action="<?php echo $this->url('admin',array('action'=>'orderfinalizing'));?>">
        
         <label for="creditcard">Credit card</label>
        <select name="creditcard" id="creditcard" class="required">
            <option value=""></option>
            <?php foreach($this->creditcards as $item):?>
                <option value="<?php echo $item->getCreditcard();?>" <?php echo $item->getCreditcard()==$this->creditcard->getCreditcard()?'selected':'';?>><?php echo $item->getCreditcard();?></option>
            <?php endforeach; ?>
        </select>
        <input type="text" id="holder" value="<?php echo $this->creditcard->getHolder();?>" disabled />
        <input class="btn" type="submit" name="btnShow" value="Show">               
       <hr/>                  
        
       <div id="divOrders">
            <table class="table" id="orderInfo">
                <thead>		
                  
    				<tr>
    					<th style="width: 30px;"><div class="soNo">#</div></th>
    					<th  ><div>OrderNo</div></th>
    					<th  style="width: 160px;"><div>Date</div></th>
    					<th style="width: 80px;"><div>Admin</div></th>
    					<th style="width: 100px;"><div>Store</div></th>  					 
    					 
    					<th style="width: 40px;"><div class="soItems">Items</div></th>
    					<th style="width: 40px;"><div class="soItems">Discount</div></th>
    					<th style="width: 40px;"><div class="soItems">Tax</div></th>
    					<th style="width: 40px;"><div class="soItems">Ship US</div></th>
    					<th style="width: 40px;"><div class="soTotalWeb">Total Web</div></th>
    					<th style="width: 60px;"><div class="soTotalWeb1">Total Web1</div></th>
    					<th style="width: 60px;"><div class="soTotalFinal">Total Final</div></th>
    					<th style="width: 40px;"><div>#item cancel</div></th>
    					<th style="width: 60px;"><div>Total cancel</div></th>
    					<th style="width: 60px;"><div title="Total final - Total cancel">Final</div></th>    
    					<th style="width: 80px;">-</th>					    
    				</tr>
			 </thead>
			 <tbody>
			 <?php $i = 1;?>
			 <?php foreach ($this->orders as $item):?>
			     <tr class='trItem '>
			           <td class="stt"><?php echo $i++;?></td>
			           <td><a target="_blank" href="<?php echo $this->url('admin',array('action'=> 'vieworder','id'=> $item->getOrderno()));?>">
			             <?php echo $item->getOrderno();?></a>
			            <input type="hidden" class="orderno" value="<?php echo $item->getOrderno();?>" />
			            </td>
			           <td><?php echo date("d-m-Y",strtotime($item->getOrderdate()));?></td>
			           <td><?php echo $item->getAdmin();?></td>
			           <td><?php echo $item->getStore_name();?></td>
			           
			           
			           <td class="number_format"><?php echo $item->getItems();?></td>
			           <td class="number_format"><?php echo number_format($item->getDiscount(),2,".",',');?></td>
			           <td class="number_format"><?php echo number_format($item->getTax(),2,".",",");?></td>
			           <td class="number_format"><?php echo number_format($item->getShip_us(),2,".",",");?></td>
			           <td class="number_format"><?php echo number_format($item->getTotal_web(),2,".",".");?></td>
			           <td class="number_format "><?php echo number_format($item->getTotal_web1(),2,".",',');?></td>
			           <td class="number_format highlight"><?php echo number_format($item->getTotal_final(),2,".",",");?></td>
			           <td class="number_format"><?php echo $item->getCancelled_items();?></td>
			           <td class="number_format"><?php echo number_format($item->getTotal_cancelled(),2,".",',');?></td>
			           <td class="number_format highlight"><?php echo number_format($item->getPaid(),2,'.',',');?></td>
			           <td class="check">
			             <a class="changecreditcard" title="Change Credit Card" 
			                 href="#" data-url="<?php echo $this->url('admin',array('action'=>'updatecreditcard'));?>"
			                 data-orderno="<?php echo $item->getOrderno();?>"
			               >
			                 <span class="icon-edit"></span>
			             </a>
			              
			             <a class="finalize" title="Finalize" 
			                 href="<?php echo $this->url('admin',array('action'=>'finalizeorderajax','id'=>$item->getOrderno()));?>">
			                 <span class="icon-check"></span>
			             </a>
			          </td>
			           
			     </tr>
			  <?php endforeach;?>
			 </tbody>
			 <tfoot>
			     <tr>
			         <td colspan="17"></td>
			     </tr>
			 </tfoot>
            </table>
       </div>
 
	</form>
	
	<div id="divUpdateForm">
           <div id="creditcard_order">
           	
           	<label for="orderno">OrderNo</label>
           	<input type="text" id="orderno_dialog" name="orderno" disabled />
           	  
            <label for="creditcard_update">Credit card</label>
            <select name="creditcard_update" id="creditcard_update">
                <option value=""></option>
                <?php foreach($this->creditcards as $item):?>
                    <option value="<?php echo $item->getCreditcard();?>"><?php echo $item->getCreditcard();?></option>
                <?php endforeach; ?>
            </select>
           </div>
          <br/>      
          <input type="hidden" name="current_creditcard" id="current_creditcard"  value="" />         
        <input type="text" name="card_holder" id="card_holder"  maxlength="255"  disabled />
        <hr/>         
	</div>
	
</div>
 