 <?php if (!$this->isAjaxRequest):?>
 
<?php  
        $this->headScript()->appendFile($this->basePath() . '/js/admin/tongthukh.js'); 
        $this->headLink()->prependStylesheet($this->basePath() . '/css/admin/tongthukh.css');
        
        $title = 'Tổng thu của KH';
        $this->headTitle($title);
       
        
 ?>

 <form action="<?php echo $this->url('admin',array('action'=>'tongthukh')); ?>" method="post" id="frmTongthuKH">
 <div class="row">    
   <div class="span11">
          <div id="divTongThuKH">  
 <?php endif;?>   
            <h3>TỔNG THU TỪ KHÁCH HÀNG</h3>          
             <input type="hidden" name="page" id="page" value="<?php echo $this->page; ?>" />    
        		<table class="table" id="shippingTotalTable">
        			<thead>
        				<tr>
        					<th style="width: 30px;">#</th>        					
        					<th >Shipment</th>
        					<th style="width: 80px;">Total (1)</th>
        					<th style="width: 80px;">Total Cancel(2)</th>
        					<th style="width: 100px;">Total Final(3)</th>
        					<th style="width: 110px;">Shipping Fee(4)</th> 
        					<th style="width: 100px;"> Lỗ tạm tính(5)</th>        					 
        				</tr>
        			</thead>
        			<tbody>
        			<?php $i = 1; ?>        			  
        		 
        			 <?php foreach ($this->paginator as $item):?>     
        			  <?php if (!($this->UserInfo()->getUserGroup() == 'group2') && $item->getShipment_id() > 23): ?>    			         
    			    	<tr class="trItem">
    			    		<td class="soNo">
    			    		  <div class="soNo">
    			    		       <?php echo $i++; ?>
    			    		  </div>          			    		  
    			    		</td>        			    		 
    			    		<td>
			    		       <div class=""><?php echo $item->getShipment_name();?>
			    		           <input type="hidden" name="shipment_id" value="<?php echo $item->getShipment_id();?>"/>
			    		       </div>
    			    		</td>
    			    		<td ><div class="curency "><?php echo number_format($item->getTotal(),2,".",",");?></div></td> 
    			    		<td ><div class="curency"><?php echo number_format($item->getCancel(),2,".",",");?></div></td>        			    		
    			    		<td ><div class="curency total"><?php echo number_format($item->getTotal_final(),2,".",",");?></div></td>        			    		
    			    		<td ><div class="curency "><?php echo number_format($item->getShipping_fee(),2,".",",");?></div></td>  
    			    		<td ><div class="curency total"><?php echo number_format($item->getLotamtinh(),2,".",",");?></div></td> 
    			    		
    			    	</tr>      			    	
        			 <?php endif;?>  
        			 
        			  <?php if ($this->UserInfo()->getUserGroup() == 'group2'): ?>    			         
    			    	<tr class="trItem">
    			    		<td class="soNo">
    			    		  <div class="soNo">
    			    		       <?php echo $i++; ?>
    			    		  </div>          			    		  
    			    		</td>        			    		 
    			    		<td>
			    		       <div class=""><?php echo $item->getShipment_name();?>
			    		           <input type="hidden" name="shipment_id" value="<?php echo $item->getShipment_id();?>"/>
			    		       </div>
    			    		</td>
    			    		<td ><div class="curency "><?php echo number_format($item->getTotal(),2,".",",");?></div></td> 
    			    		<td ><div class="curency"><?php echo number_format($item->getCancel(),2,".",",");?></div></td>        			    		
    			    		<td ><div class="curency total"><?php echo number_format($item->getTotal_final(),2,".",",");?></div></td>        			    		
    			    		<td ><div class="curency "><?php echo number_format($item->getShipping_fee(),2,".",",");?></div></td>  
    			    		<td ><div class="curency total"><?php echo number_format($item->getLotamtinh(),2,".",",");?></div></td> 
    			    		
    			    	</tr>      			    	
        			 <?php endif;?>  
        			 <?php endforeach;?>
        			 
        			</tbody>
        			<tfoot> 
        			    <tr>
                            <td colspan="7">
                                 <?php    
                                    $url = $this->url('admin', array('action'=>'tongthukh'));
                                            echo $this->paginationControl(
                                                        $this->paginator, 'Sliding', 'paginator-slide', 
                                                        array('url'=>$url,'action'=>'tongthukh')
                                    );
                                ?>   
                            </td>
                         </tr>
        			</tfoot>
        		</table> 
<?php if (!$this->isAjaxRequest):?>        		          
             </div>
         </div>
    </div>
 </form>
<?php endif;?>