 <?php if (!$this->isAjaxRequest):?>
 <?php  
        $this->headScript()->appendFile($this->basePath() . '/js/admin/tongtienhang.js'); 
        $this->headLink()->prependStylesheet($this->basePath() . '/css/admin/tongtienhang.css');
        
        $title = 'Tổng Tiền Hàng Theo Đợt';
        $this->headTitle($title);
        
        
 ?>

<form action="<?php echo $this->url('admin',array('action'=>'tongtienhang')); ?> " method="post" id="frmTongtienhang" >
     <div class="row">    
       <div class="span11">
              <div id="divTongtienhang"> 
 <?php endif;?>    
                <h3>TỔNG TIỀN HÀNG THEO ĐỢT</h3>      
                    <input type="hidden" name="page" id="page" value="<?php echo $this->page; ?>" />         
            		<table class="table" id="shippingTotalTable">
            			<thead>
            				<tr>
            					<th style="width: 30px;">#</th>        					
            					<th >Shipment</th>
            					<th style="width: 80px;">Total (1)</th>
            					<th style="width: 120px;">Total Cancel (2)</th>
            					<th style="width: 100px;">Total Final (3)</th>
            					<th>-</th>        					 
            				</tr>
            			</thead>
            			<tbody>
            			<?php $i = 1; ?>        			  
            		 
            			 <?php foreach ($this->paginator as $item):?>       
            			  <?php if (!($this->UserInfo()->getUserGroup() == 'group2') && $item->getShipment_id() > 23): ?>   			         
        			    	<tr class="trItem">
        			    		<td class="soNo">
        			    		  <div class="soNo">
        			    		       <?php echo $i++; ?>
        			    		  </div>          			    		  
        			    		</td>        			    		 
        			    		<td>
    			    		       <div class=""><?php echo $item->getShipment_name();?>
    			    		           <input type="hidden" name="shipment_id" value="<?php echo $item->getShipment_id();?>"/>
    			    		       </div>
        			    		</td>
        			    		<td ><div class="curency "><?php echo number_format($item->getTotal(),2,".",",");?></div></td> 
        			    		<td ><div class="curency"><?php echo number_format($item->getCancel(),2,".",",");?></div></td>        			    		
        			    		<td ><div class="curency total"><?php echo number_format($item->getTotal_final(),2,".",",");?></div></td>       			    		
        			    		 
        			    		<td ><div class="curency">-</div></td> 
        			    		
        			    	</tr>      			    	
            			   <?php endif; ?>
            			   
            			    <?php if ($this->UserInfo()->getUserGroup() == 'group2'): ?>   			         
        			    	<tr class="trItem">
        			    		<td class="soNo">
        			    		  <div class="soNo">
        			    		       <?php echo $i++; ?>
        			    		  </div>          			    		  
        			    		</td>        			    		 
        			    		<td>
    			    		       <div class=""><?php echo $item->getShipment_name();?>
    			    		           <input type="hidden" name="shipment_id" value="<?php echo $item->getShipment_id();?>"/>
    			    		       </div>
        			    		</td>
        			    		<td ><div class="curency "><?php echo number_format($item->getTotal(),2,".",",");?></div></td> 
        			    		<td ><div class="curency"><?php echo number_format($item->getCancel(),2,".",",");?></div></td>        			    		
        			    		<td ><div class="curency total"><?php echo number_format($item->getTotal_final(),2,".",",");?></div></td>       			    		
        			    		 
        			    		<td ><div class="curency">-</div></td> 
        			    		
        			    	</tr>      			    	
            			   <?php endif; ?>
            			 <?php endforeach;?>
            			 
            			</tbody>
            			
            			<tfoot>
    	                <tr>
                            <td colspan="7">
                                 <?php    
                                    $url = $this->url('admin', array('action'=>'tongtienhang'));
                                            echo $this->paginationControl(
                                                        $this->paginator, 'Sliding', 'paginator-slide', 
                                                        array('url'=>$url,'action'=>'tongtienhang')
                                    );
                                ?>   
                            </td>
                         </tr>
    	               </tfoot>        			
            			 
            		</table>    
 <?php if (!$this->isAjaxRequest):?>        	        
              </div>
       </div>
    </div>
  </form>
<?php endif;?>