<?php if (!$this->isAjaxRequest):?>
<?php  
        $this->headScript()->appendFile($this->basePath() . '/js/admin/transfermgm.js'); 
        $this->headScript()->appendFile($this->basePath() . '/js/jshashtable-3.0.js');
        $this->headScript()->appendFile($this->basePath() . '/js/jquery.numberformatter-1.2.3.js');
        
        $this->headLink()->prependStylesheet($this->basePath() . '/css/admin/transfermgm.css');
        
       
        $this->headTitle('Quản lý chuyển khoản');
        $title = 'Quản lý chuyển khoản';
        
 ?>
 <?php 
    $source = "" ;
    foreach($this->nicks  as $item){
        $source .= '"'. $item['nick'] . '",';
    }
    
    $source = substr($source,0,strlen($source) -1 );
    
 ?>
                
            
 
<script>
var data = [<?php echo $source;?>]; 
</script>
 

   <div class="span2">
     <h4>Danh sách Khách hàng</h4>
     <div id="nicks">
        <ul class="list">
             <li class="nicks" id="">Tất cả</li>
            <?php foreach($this->nicks  as $item):?>
                <li class="nicks" id="<?php echo $item['nick'];?>"><?php echo $item['nick'];?></li>
            <?php endforeach;?>
           
            
        </ul>
     </div>
        
   </div>
   <div class="span9">
       
         <form action ="<?php echo $this->url('admin', array('action'=>'transfermgm'));?>" 
                name="transferMgmForm"
                method="post" id="transferMgmForm">
                
            <span>Nick: <input type="text" name="search_nick" id="search_nick" /></span> <input type="button" name="search" id="search" value="Tìm" class="btn" />
            <h4>Thông tin chuyển khoản</h4>    
            <div id="transList">
 <?php endif;?>            
            <input type="hidden" name="page" id="page" value="<?php echo $page; ?>" />            
            <table class="table">
            <thead>
               <tr>
                     
                    <th>#</th>
                    <th>Nick</th>
                    <th>Ngày nhập</th>   
                    <th>Ngày chuyển</th>  
                    <th>Refno</th>                 
                    <th>Tỷ giá</th>                    
                    <th>VNĐ</th>      
                    <th>USD</th>
                    <th>Ghi chú</th>
                    <th>Xác nhận</th>
                    <th>Xóa</th>                      
               </tr>            
            </thead>
            <tbody>
                <?php $i = ($page -1)* $row + 1 ;?>
                <?php foreach($paginator as $item):?>
               <tr class="<?php echo $item->getStatus();?>">
                    <td class="no"><?php echo $i++; ?></td>
                    <td><?php echo $item->getNick();?></td>                    
                    <td >
                       <?php echo date('d-m-Y H:i:s',strtotime($item->getDatecreated()));?>
                     </td>
                     <td><?php echo date('d-m-Y',strtotime($item->getTrans_date())); ?></td>
                     <td><?php echo $item->getRefno(); ?></td>
                     <td style="text-align: right;" ><?php echo number_format($item->getX_rate(),0,'.',','); ?></td>
                     <td style="text-align: right; color:#c70000; font-weight:bold;"><?php echo number_format($item->getVnd(),0,'.',','); ?></td>
                     <td style="text-align: right;"><?php echo number_format($item->getUsd(),2,'.',','); ?></td>
                     <td><div class="divNote"><?php echo $item->getNote();?></div></td>   
                                 
                    <td style="text-align: center;">                       
                        <a title="Xác nhận" class="confirmTrans" href="<?php echo $this->url('admin',array('action'=>'confirmtransfer','id'=> $item->getId()));?>"><span class="icon-check"></span></a>
                    </td>
                    <td>
                        <a title="Xóa bỏ" class="delTrans" href="<?php echo $this->url('admin',array('action'=>'deltransfer','id'=> $item->getId()));?>"><span class="icon-trash"></span></a> 
                    </td> 
                      
                                
                    
               </tr>
               <?php endforeach;?>
            </tbody>
            <tfoot>
                <tr>
                            <td colspan="11">
                                 <?php    
                                    $url = $this->url('admin', array('action'=>'transfermgm'));
                                            echo $this->paginationControl(
                                                        $paginator, 'Sliding', 'paginator-slide', 
                                                        array('url'=>$url,'action'=>'transfermgm')
                                    );
                                ?>   
                            </td>
                           </tr>
            </tfoot>
            </table>
 <?php if (!$this->isAjaxRequest):?>
        </div> 
       </form>
   </div>
    

<?php endif;?>