<?php if (!$this->isAjaxRequest):?>
<?php  
        $this->headScript()->appendFile($this->basePath() . '/js/admin/updatebalance.js'); 
        $this->headScript()->appendFile($this->basePath() . '/js/jshashtable-3.0.js');
        $this->headScript()->appendFile($this->basePath() . '/js/jquery.autosize.min.js');
        $this->headScript()->appendFile($this->basePath() . '/js/jquery.numberformatter-1.2.3.js');
        
        
        
        $this->headLink()->prependStylesheet($this->basePath() . '/css/admin/updatebalance.css');
        
       
        $this->headTitle('Cập nhật tài khoản KH');
        $title = 'Các GD khác';
        
 ?>


 

   <div class="span2" id="divTransaction">
     <h4><?php echo $this->escapeHtml($title);?></h4>
     <form name="updatebalanceForm" id="updatebalanceForm" method="post" 
                action="<?php echo $this->url('admin',array('action'=> 'updatebalance'));?>">
        
       
        
       
        <br />
        
        <label for="trans_date" >Ngày GD</label>
        <input type="text" name="trans_date" class="datepicker required" id="trans_date" />
        <div id="divNicks">
            <label for="nicks">Nick</label>
			<input type="text" name="nick" id="nicks" /> 
              
        </div>
        <div id="divOrderNo">
            <label for="orderno">OrderNo</label>
            <input type="text" name="orderno" id="orderno" data-val="" data-valid="0" maxlength="255" 
                            data-url="<?php echo $this->url('admin',array('action'=>'checkorderno'));?>" />
                     
        </div>
        
         <div id="divShipments">
            <label for="shipment">Shipment</label>
             <select name="shipment" id="shipment">
                   <option value=""></option>
                   <?php foreach ($this->shipments as $item):?>
                    <option value="<?php echo $item->getId();?>"><?php echo $item->getShip_name();?></option>
                   <?php endforeach;?>
             </select>         
        </div>
        
        <input type="hidden"  id="nick_name" value=""/>
         
        <label for="vnd">Số tiền USD</label> 
        <input type="text" name="usd" class="required" id="usd" onkeypress="return checkIsNumberKey(event)" maxlength="8" data-info="Nhập vào số tiền cần chuyển bằng VNĐ." />
        <label for="note">Lý do</label>
        <textarea rows="3" cols="" name="note" id="note"></textarea>      
       <div id="errormsg"> <?php echo $this->errmsg;?></div>
        <hr/>
        
        <label for="submitbutton"></label>
        <input type="hidden" value="saveTrans" name="saveTrans" />
        <input class="btn" type="submit" name="btnSubmit" id="btnSubmit" value=" Submit " disabled />
     </form>
   </div>
   <div class="span9">
        <div id="divTitle">            
            <h4>Các GD gần đây</h4>
        </div>
         <form action ="<?php echo $this->url('admin', array('action'=>'updatebalance'));?>" 
                name="updatebalanceInfoForm"
                method="post" id="updatebalanceInfoForm">
                
            
            <div id="divDateFilter">
                Date: <input type="text" name="date_ftiler" id="date_filter" class="datepicker"/>
            </div>
            
            <div id="divAdminFilter">


            Admin: 
            <select name="admin_filter" id="admin_filter">
                <option value=""></option>
                 <?php foreach ($this->admins as $item):?>
                    <option value="<?php echo $item->getNick();?>"><?php echo $item->getNick();?></option>
                 <?php endforeach;?>
            </select>
           </div>  
          
           <div id="divNickFilter">
            Nick: <input type="text"  name="nick_filter" id="nick_filter" />
            
           </div>    
            <input type="submit" value="Submit" class="btn" id="btnFilter"/>   
            <div id="transList">
 <?php endif;?>            
            <input type="hidden" name="page" id="page" value="<?php echo $this->page; ?>" />  
               
         
            <table class="table">
            <thead>
               <tr>  
                    <th>#</th>
                    <th style="width: 75px; text-align: center;">Ngày</th>                         
                    <th>Admin</th>
                    <th>Nick</th>                    
                    <th>Trừ</th>                
                    <th>Cộng</th>
                    <th>Số dư TK</th>
                    <th>Ghi chú</th>                                    
               </tr>            
            </thead>
            <tbody>
                <?php $i = ($this->page -1)* $this->row + 1 ;?>
                <?php foreach($this->paginator as $item):?>
               <tr>
                    
                    <td><?php echo $i++; ?></td>
                    <td style="width: 75px; text-align: center;"><?php echo date('d-m-Y', strtotime($item->getDate()));?></td>            
                    <td><?php echo $item->getAdmin();?></td>
                    <td><?php echo $item->getNick();?></td>
                    <td style="text-align: right;"><?php echo $item->getType()=="-"?number_format($item->getAmount(),2,".",","):"-";?></td>
                    <td style="text-align: right;"><?php echo $item->getType()=="+"?number_format($item->getAmount(),2,".",","):"-";?></td>
                    <td style="text-align: right;"><?php echo number_format($item->getCredit(),2,".",",");?></td>
                    <td><?php echo $item->getNote();?></td>
               </tr>
               <?php endforeach;?>
            </tbody>
            <tfoot>
                <tr>
                            <td colspan="11">
                                 <?php    
                                    $url = $this->url('admin', array('action'=>'updatebalance'));
                                            echo $this->paginationControl(
                                                        $this->paginator, 'Sliding', 'paginator-slide', 
                                                        array('url'=>$url,'action'=>'updatebalance')
                                    );
                                ?>   
                            </td>
                           </tr>
            </tfoot>
            </table>
 <?php if (!$this->isAjaxRequest):?>
        </div> 
       </form>
   </div>
   
  

<?php endif;?>