<?php if (!$this->isAjaxRequest):?>
<?php  
        $this->headScript()->appendFile($this->basePath() . '/js/admin/viewshipment.js'); 
        $this->headScript()->appendFile($this->basePath() . '/js/jquery.autosize.min.js');
        $this->headScript()->appendFile($this->basePath() . '/js/jshashtable-3.0.js');
        $this->headScript()->appendFile($this->basePath() . '/js/jquery.numberformatter-1.2.3.js');
          
        $this->headScript()->appendFile($this->basePath() . '/js/jquery.mousewheel.pack.js');
        $this->headScript()->appendFile($this->basePath() . '/js/fancybox/jquery.fancybox.js');
        $this->headScript()->appendFile($this->basePath() . '/js/fancybox/jquery.fancybox-buttons.js');
        $this->headScript()->appendFile($this->basePath() . '/js/fancybox/jquery.fancybox-thumbs.js');
        
        
        
        $this->headLink()->prependStylesheet($this->basePath() . '/css/admin/viewshipment.css');

 
        $this->headLink()->prependStylesheet($this->basePath() . '/css/fancybox/jquery.fancybox.css');
        $this->headLink()->prependStylesheet($this->basePath() . '/css/fancybox/jquery.fancybox-buttons.css');
        $this->headLink()->prependStylesheet($this->basePath() . '/css/fancybox/jquery.fancybox-thumbs.css');
        
        
        $title = 'Đợt hàng';
        $this->headTitle($title);
       
   
 ?>
 
<script>
   var users = [<?php //echo $users;?>]; 
</script>


<div class="span11">
	<form name="frmShipment" id="frmShipment" method="post"
		action="<?php echo $this->url('admin',array('action'=>'shipped'));?>">
		<h4>Thông tin Đợt hàng</h4>
	    <div id="shipmentInfo">		
			  <table>
			     <tr>
			         <td>
			            <input readonly type="hidden" name="id" id="ship_id" value="<?php echo $this->shipment->getId();?>" />
				       	<label for="ship_date">Date</label>
				       	<input readonly type="text" name="ship_date" id="ship_date" class="datepicker" value="<?php 
				       		if (($this->shipment->getShip_date())){
				       			echo date("d-m-Y",strtotime($this->shipment->getShip_date()));
				       		}?>" />
			         </td>
			         <td>
			             <label for="ship_name">Name</label><input  readonly type="text" name="ship_name" id="ship_name" value="<?php echo $this->shipment->getShip_name();?>" />
			         </td>
			         <td><label for="weight">Weight (lbs)</label><input readonly type="text" name="weight" value="<?php echo $this->shipment->getWeight()==""?"":number_format($this->shipment->getWeight(),2,'.',',');?>" id="weight"/></td>
			         
			     </tr>
				 
				 <tr>
				    <td colspan="3">
				        <label for="note">Note</label> <textarea readonly name="note" id="note" ><?php echo $this->shipment->getNote();?></textarea>
				    </td>
				 </tr>
				 
			 	 
	       	  </table>
			 
			
			<div id="nextstep">	
			  
			</div>  
	   </div>
		
		<hr/>
<?php endif;?>
	<?php if ($this->shipment->getId()):?>	
	  <?php if (!$this->isAjaxRequest):?>
		<div id="divShipingOrder">
      <?php endif;?>
        		 
        	 <div id="anchor"></div>        	              
            <div id="shipmentList">
               <div id="divTableHeader"></div>
        		<table class="table" id="shipmentTable">
        			<thead>
        				<tr>
        					<th><div class="soNo">#</div></th>
        					<th ><div class="divDescription">OrderNo</div></th>
        					<th><div class="soOrderdate">OrderDate</div></th>
        					<th><div class="soStoreName">Store</div></th>
        					<th><div class="soHolder">Holder</div></th>
        					<th><div class="soItems">Items</div></th>
        					<th><div class="soDiscount">Discount</div></th>        					
        					<th><div class="soTotal_web">Total Web</div></th>
        					<th><div class="soTotal_web1">Total Web1</div></th>
        					<th><div class="soShipUS">Ship US</div></th>
        					<th><div class="soTax">Tax</div></th>
        					<th><div class="soTotalFinal">Total Final</div></th>
        					<th><div class="soPackageno"># Thùng</div></th>
        					<th><div class="soNote2">Note</div></th>
        					<th><div class="soTotalWeb2">Total web</div></th>
        					<th><div class="soTotalWeb21">Total web1</div></th>
        					<th><div class="soItems2">Items</div></th>
        					<th><div class="soTotalFinal2">Total final</div></th>
        					
        				</tr>
        			</thead>
        			<tbody>
        			 <?php 
        			         $i = 1; 
        			         $total_web = 0;
        			         $total_web1 = 0; 
        			         $total_items  = 0;        			         
        			         $total_final = 0;
        			         
        			         $total_web_dung = 0;
        			         $total_web1_dung = 0;
        			         $total_final_dung = 0;
        			         $total_items_dung = 0;
        			         
        			         $total_dung = 0;
        			  ?>
        			<?php if ($this->shipmentOrders):?>
        			  
        			    <?php foreach ($this->shipmentOrders as $item):?>
        			    
        			    <?php 
        			    	
        			    	if ($item->getHolder() == "DUNG"){
                                                             
        			    		$total_dung += $item->getTotal_final_o();
        			    	}
        			    	
        			    	$total_web_dung += $item->getTotal_web();
        			    	$total_web1_dung += $item->getTotal_web1();
        			    	$total_final_dung += $item->getTotal_final();
        			    	$total_items_dung += $item->getItems();
        			    	
        			    	$total_items += $item->getItems_o();
        			    	$total_web += $item->getTotal_web_o();
        			    	$total_web1 += $item->getTotal_web1_o();
        			    	$total_final += $item->getTotal_final_o();
        			    	
        			    ?>
        			    	<tr class="trItem">
        			    		<td>
        			    		  <div class="soNo">
        			    		       <?php echo $i++; ?>
        			    		  </div>          			    		  
        			    		</td>
        			    		<td>
        			    		   <div class="divDescription">
            			    		       <div >
                        	     		    <?php if (!empty($item->images)):?>
                        	     		       <?php 
                        	     		            $images = $item->images;
                        	     		            $img = array_shift($images);
                        	     		             
                        	     		       ?> 
                        	     		       <a class="fancybox" data-fancybox-group="thumb_<?php echo $item->getOrderno();?>" href="<?php echo $img->getPath();?>"><?php echo $item->getOrderno();?></a>
                        	     		       
                        	     		       
                        	     		       <?php  foreach($images as $img):?>
                        	     		            <a class="hidden btn fancybox" data-fancybox-group="thumb_<?php echo $item->getOrderno();?>" href="<?php echo $img->getPath();?>"></a>
                        	     		       <?php endforeach;?>
                        	     		    <?php else: ?>
                        	     		    <?php echo $item->getOrderno();?>
                        	     		    <?php endif;?>
                	     		        </div>
                	     		    </div>
        			    		</td>
        			    		<td><div class="soOrderdate"><?php echo $item->getOrderdate();?></div></td>
        			    		<td><div class="soStoreName"><?php echo $item->getStore_name();?></div></td>
        			    		<td><div class="soHolder"><?php echo $item->getHolder();?></div></td>
        			    		<td><div class="soItems"><?php echo $item->getItems_o();?></div></td>
        			    		<td><div class="soDiscount"><?php echo number_format($item->getDiscount(),2,'.',',');?></div></td>
        			    		<td><div class="soTotal_web"><?php echo number_format($item->getTotal_web_o(),2,'.',',');?></div></td>
        			    		<td><div class="soTotal_web1"><?php echo number_format($item->getTotal_web1_o(),2,'.',',');?></div></td>
        			    		<td><div class="soShipUS"><?php echo number_format($item->getShip_us(),2,'.',',');?></div></td>
        			    		<td><div class="soTax"><?php echo number_format($item->getTax(),2,'.',',');?></div></td>
        			    		<td><div class="soTotalFinal"><?php echo number_format($item->getTotal_final_o(),2,'.',',');?></div></td>
        			    		<td><input readonly type="text" name="<?php echo $item->getOrderno();?>_package" class="packageno" value="<?php echo $item->getPackage();?>"/></td>
        			    		<td><textarea readonly rows="1" cols="" class="soNote" name="<?php echo $item->getOrderno();?>_note"><?php echo $item->getNote();?></textarea></td>
        			    		<td>
        			    		    <input readonly class="total_web" type="text" name="<?php echo $item->getOrderno();?>_total_web"
            			    	            value="<?php echo $item->getTotal_web()=="0"?"":number_format($item->getTotal_web(),2,".",",");?>" />
        			    		</td>
        			    		<td>
        			    		   <input readonly class="total_web1" type="text" name="<?php echo $item->getOrderno();?>_total_web1" 
            			    	             value="<?php echo $item->getTotal_web1()=="0"?"":number_format($item->getTotal_web1(),2,".",",");?>" />
        			    		</td>
        			    		<td>
        			    		   <input readonly class="items" type="text" name="<?php echo $item->getOrderno();?>_items"   
            			    	            value="<?php echo $item->getItems()=="0"?"":number_format($item->getItems(),0,".",",");?>" maxlength="4"/>
        			    		</td>
        			    		<td>
        			    		   <input readonly class="total_final" type="text" name="<?php echo $item->getOrderno();?>_total_final"  
            			    	            value="<?php echo $item->getTotal_final()=="0"?"":number_format($item->getTotal_final(),2,".",",");?>" />
        			    		</td>
        			    		
        			    	</tr>
        			    	
        			    
        			    <?php endforeach;?>
        			<?php endif;?>
        			</tbody>
        			<tfoot>
        				<?php if ($this->shipmentOrders):?>
        				<tr id="totalRow">
        				    <td id="tdTotal" colspan="5">Total</td>
        				    <td class="val"><span class="label"><?php echo number_format($total_items,0,".",",");?></span></td>
        				    <td>&nbsp;</td>
        				    <td class="val"><span class="label"><?php echo number_format($total_web,2,".",",");?></span></td>
        				    <td class="val"><span class="label"><?php echo number_format($total_web1,2,".",",");?></span></td>
        				    <td>&nbsp;</td>
        				    <td>&nbsp;</td>
        				    <td class="val"><span class="label"><?php echo number_format($total_final,2,".",",");?></span></td>
        				    <td>&nbsp;</td>
        				    <td>&nbsp;</td>
        				    <td class="val"><span class="label"><?php echo number_format($total_web_dung,2,".",",");?></span></td>
        				    <td class="val"><span class="label"><?php echo number_format($total_web1_dung,2,".",",");?></span></td>
        				    <td class="val"><span class="label"><?php echo number_format($total_items_dung,0,".",",");?></span></td>
        				    <td class="val"><span class="label"><?php echo number_format($total_final_dung,2,".",",");?></span></td>
        				    <td id="lastcell">&nbsp;</td>
        				</tr>
        				<tr>
        					<td colspan="18" id="sumarize">
        					    <?php foreach($this->cards as $item):?>
        					    <span class="label right"><?php echo $item['card']?>: </span><span class="val"><?php echo number_format($item['total'],2,'.',',');?></span> <br/>       					    
        					    <?php endforeach;?>
        					    <span class="label right">Total: </span><span class="val red"><?php echo number_format($total_dung,2,'.',',');?></span> <br/>
        						<span class="label ">Total Web1: </span><span class="val red"><?php echo number_format($total_web1,2,'.',',');?></span> <br/>
        						<span class="label">Total Final: </span><span class="val red"><?php echo number_format($total_final,2,'.',',');?></span> <br/>
        						
        					</td>
        				</tr>
        				<?php endif;?>
        			     <tr>
        			         <td colspan="2">
        			             <br/>
        			         </td>    
        			         <td colspan="2" >
        			             <br/>        			         	  
        			              <input type="submit" value="Back" class="btn" />
        			         </td>
        			         
        			         <td colspan="11">
        			             
        			         </td>
        			     </tr>
        			</tfoot>
        		</table>           
            	</div>
         	 <?php if (!$this->isAjaxRequest):?>  
                </div>
             <?php endif;?>
          <?php endif;?>
 <?php if (!$this->isAjaxRequest):?>  
	</form>

</div>
 
<?php endif;?>


