<?php if (!$this->isAjaxRequest):?>
 <?php  
        $this->headScript()->appendFile($this->basePath() . '/js/admin/viewcustomerorder.js'); 
        $this->headScript()->appendFile($this->basePath() . '/js/jquery.autosize.min.js');
        
        
        $this->headLink()->prependStylesheet($this->basePath() . '/css/admin/viewcustomerorder.css');
      
        
        $title = 'Thông tin đặt hàng';
        $this->headTitle($title);
       
        
 ?>

  <form action ="<?php echo $this->url('admin', array('action'=>'viewcustomerorder'));?>" 
                name="orderForm"
                method="post" id="orderForm">
   
     
 
  <div class="span9">
        <h4><?php echo $this->escapeHtml($title);?></h4>      
        
        <div id="divNicks">
            <label for="nicks">Nick</label>
             <select name="nick" id="nicks"  class="required">
                   <option value=""></option>
                   <?php foreach ($this->customers as $item):?>
                    <option <?php echo $item->getNick()==$this->user->getNick()?'selected':'';?> value="<?php echo $item->getNick();?>"><?php echo $item->getNick();?></option>
                   <?php endforeach;?>
             </select>         
             
             <input type="submit" class="btn" name="btnShow" id="btnShow" value="Show" />
        </div>
        
        <hr />
        
           <div id="orderList">        
<?php endif;?>
            
          <?php if ($this->user->getNick()):?>
                 
            <input type="hidden" name="page" id="page" value="<?php echo $this->page; ?>" />            
            <table class="table">
            <thead>
               <tr>                     
                    <th style="width: 25px;">#</th> 
                    <th style="width: 80px;">Ngày</th>                   
                    <th>Store</th>                   
                    <th>Mô tả</th>
                    <th>Ghi chú</th>
                    <th style="width: 80px;">Trạng thái</th>
                                          
               </tr>            
            </thead>
            <tbody>
                <?php $i = ($this->page -1)* $this->row + 1 ;?>
                <?php foreach($this->paginator as $item):?>
               <tr>
                    <td style="text-align:center;"><?php echo $i++; ?></td>
                    <td ><div class="divDate"><?php echo date('d-m-Y',strtotime($item->getDatecreated()));?></div></td>
                    <td ><?php echo $item->getStore_name();?></td>
                    <td><div class="divDescription"><?php echo $item->getDescription(); ?></div></td>
                    <td ><div class="divNote"><?php echo $item->getNote();?></div></td> 
                    <td ><?php echo $item->getStatus();?></td>  
               </tr>
               <?php endforeach;?>
            </tbody>
            <tfoot>
                <tr>
                            <td colspan="6">
                                 <?php    
                                    $url = $this->url('admin', array('action'=>'viewcustomerorder'));
                                            echo $this->paginationControl(
                                                        $this->paginator, 'Sliding', 'paginator-slide', 
                                                        array('url'=>$url,'action'=>'viewcustomerorder')
                                    );
                                ?>   
                            </td>
                           </tr>
            </tfoot>
            </table>
      <?php endif;?>
<?php if (!$this->isAjaxRequest):?>
        </div> 
       
    </div>
 </form>
<?php endif;?>


 
    
