<?php if (!$this->isAjaxRequest):?>
<?php  
        $this->headScript()->appendFile($this->basePath() . '/js/admin/viewcustomertransfer.js'); 
        $this->headScript()->appendFile($this->basePath() . '/js/jshashtable-3.0.js');
        $this->headScript()->appendFile($this->basePath() . '/js/jquery.autosize.min.js');
        $this->headScript()->appendFile($this->basePath() . '/js/jquery.numberformatter-1.2.3.js');
        
        
        
        $this->headLink()->prependStylesheet($this->basePath() . '/css/admin/viewcustomertransfer.css');
        
       
        $this->headTitle('Thông tin chuyển khoản');
        $title = 'Thông tin CK';
        
 ?>
   <form action ="<?php echo $this->url('admin', array('action'=>'viewcustomertransfer'));?>" 
                name="transferInfoForm"
                method="post" id="transferInfoForm"> 
   <div class="span9">
         <div id="divNicks">
            <label for="nicks">Nick</label>
             <select name="nick" id="nicks"  class="required">
                   <option value=""></option>
                   <?php foreach ($this->customers as $item):?>
                    <option <?php echo $item->getNick()==$this->user->getNick()?'selected':'';?> value="<?php echo $item->getNick();?>"><?php echo $item->getNick();?></option>
                   <?php endforeach;?>
             </select>         
             
             <input type="submit" class="btn" name="btnShow" id="btnShow" value="Show" />
        </div>
        
        <hr />
      <div id="List">
  <?php endif;?>  
     <?php if ($this->user->getNick()):?>
        <div id="divTitle">
            <h4><span class="label">Số dư trong tài khoản:</span><span class="rate val"><?php echo number_format($this->balance->getCredit(),2,'.',',');?> USD</span></h4>
            <h4>Lịch sử chuyển khoản</h4>
        </div>
             
            <input type="hidden" name="page" id="page" value="<?php echo $this->page; ?>" />            
            <table class="table">
            <thead>
               <tr>
                     
                    <th>#</th>
                    <th style="width: 75px; text-align: center;">Ngày nhập</th>   
                    <th style="width: 75px; text-align: center;">Ngày chuyển</th>  
                    <th>RefNo</th>
                    <th>HT CK</th>                
                    <th>Tỷ giá</th>                    
                    <th>VNĐ</th>      
                    <th>USD</th>
                    <th>Ghi chú</th>
                    <th>Trạng thái</th>                      
               </tr>            
            </thead>
            <tbody>
                <?php $i = ($this->page -1)* $this->row + 1 ;?>
                <?php foreach($this->paginator as $item):?>
               <tr class="<?php echo $item->getStatus();?>">
                    
                    <td><?php echo $i++; ?></td>
                    <td style="width: 75px; text-align: center;" >
                       <?php echo date('d-m-Y',strtotime($item->getDatecreated()));?>
                     </td>
                     <td style="width: 75px; text-align: center;"><?php echo date('d-m-Y',strtotime($item->getTrans_date())); ?></td>
                     <td><?php echo $item->getRefno(); ?></td>
                     <td style="text-align: center"><?php echo $item->getTrans_type()=="others"?"khác":$item->getTrans_type();?></td>
                     <td style="text-align: right;" ><?php echo number_format($item->getX_rate(),0,'.',','); ?></td>
                     <td style="text-align: right;"><?php echo number_format($item->getVnd(),0,'.',','); ?></td>
                     <td style="text-align: right;"><?php echo number_format($item->getUsd(),2,'.',','); ?></td>
                     <td><div class="divNote"><?php echo $item->getNote();?></div></td>
                     <td><?php echo $item->getStatus();?></td>  
               </tr>
               <?php endforeach;?>
            </tbody>
            <tfoot>
                <tr>
                            <td colspan="11">
                                 <?php    
                                    $url = $this->url('admin', array('action'=>'viewcustomertransfer'));
                                            echo $this->paginationControl(
                                                        $this->paginator, 'Sliding', 'paginator-slide', 
                                                        array('url'=>$url,'action'=>'viewcustomertransfer')
                                    );
                                ?>   
                            </td>
                           </tr>
            </tfoot>
            </table>
       <?php endif;?>
 <?php if (!$this->isAjaxRequest):?>
   </div><!-- div List  -->      
       
   </div><!-- span 9 -->
 </form>  
   <div id="divInfo">
        <span id="info"></span>
        <span id="beepernub"></span>
   </div>

<?php endif;?>