 <?php  
        $this->headScript()->appendFile($this->basePath() . '/js/customer/script.js'); 
        $this->headLink()->prependStylesheet($this->basePath() . '/css/customer/style.css');
        
        $title = '';
        $this->headTitle($title);
       
        
 ?>
 <div id="divAdd">
<?php 


 ?>
 
 <div class="row">
   <div class="span3">
     <h4><?php echo $this->escapeHtml($title);?></h4>
        span3
   </div>
   <div class="span7">
         span7
   </div>
    
    
</div>
</div>