<?php if (!$this->isAjaxRequest):?>
<?php  
        $this->headScript()->appendFile($this->basePath() . '/js/customer/storestat.js'); 
         
        $this->headLink()->prependStylesheet($this->basePath() . '/css/customer/storestat.css');
        
        
        
       
        $this->headTitle('Stores');
        $title = 'Store Đang Gom Hàng';
        
 ?>
  
   <div class="span7">
        <h4>Danh sách Store đang gom hàng</h4>
         <form action ="<?php echo $this->url('customer', array('action'=>'storestat'));?>" 
                name="storesForm"
                method="post" id="storesForm">
                Store: <select name="store_id" id="store_id">
                    <option></option>
                    <?php foreach($this->paginator as $item):?>
                    <option <?php echo $item->getId()==$this->store_id?'selected':'';?> value="<?php echo $item->getId();?>"><?php echo $item->getName();?></option>
                    <?php endforeach;?>
                </select> <input type="submit" name="btnShow" value="Show" class="btn" />
                <br/>
                <br/>
            <div id="storesList">
 <?php endif;?>            
            <input type="hidden" name="page" id="page" value="<?php echo $this->page; ?>" />            
            <table class="table">
            <thead>
               <tr>
                   
               </tr>
               <tr>
                    <th>#</th>                   
                    <th>Store</th> 
                    <th style="width: 50px; text-align: center;">#order</th>                     
               </tr>            
            </thead>
            <tbody>
                <?php $i = ($this->page -1)* $this->row + 1 ;?>
                <?php foreach($this->paginator as $item):?>
               <tr>
                    <td><?php echo $i++; ?></td>                     
                    <td><?php echo $item->getName(); ?></td>   
                    <td style="width: 50px; text-align: center;">
                       <?php echo $item->getTotal();?>
                    </td>                
               </tr>
               <?php endforeach;?>
            </tbody>
            <tfoot>
                <tr>
                            <td colspan="3">
                                 <?php    
                                    $url = $this->url('customer', array('action'=>'storestat'));
                                            echo $this->paginationControl(
                                                        $this->paginator, 'Sliding', 'paginator-slide', 
                                                        array('url'=>$url,'action'=>'storestat')
                                    );
                                ?>   
                            </td>
                           </tr>
            </tfoot>
            </table>
 <?php if (!$this->isAjaxRequest):?>
        </div> 
       </form>
   </div>

<?php endif;?>