<?php if (!$this->isAjaxRequest):?>
 <?php  
        $this->headScript()->appendFile($this->basePath() . '/js/customer/order.js'); 
        $this->headScript()->appendFile($this->basePath() . '/js/jquery.autosize.min.js');
        
        
        $this->headLink()->prependStylesheet($this->basePath() . '/css/customer/order.css');
        
/*         $this->headScript()->appendFile($this->basePath() . '/js/tinymce/tinymce.min.js');
        $this->headScript()->appendFile($this->basePath() . '/js/customer/tinymce_config.js'); */
        
        $title = 'Đặt hàng';
        $this->headTitle($title);
       
        
 ?>


  <?php 
    $source = "" ;
    foreach($this->stores  as $item){
        $source .= '"'. $item->getName() . '",';
    }
    
    $source = substr($source,0,strlen($source) -1 );
    
 ?>
 
 <script>
 var data = [<?php echo $source;?>]; 
</script>
 
 
   <div class="span11">
     <h4><?php echo $this->escapeHtml($title);?></h4>
        <form name="frmOrder" method="post" action="<?php echo $this->url('customer',array('action'=>'order'));?>">
                              
            <table class="table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Store</th>
                        <th>Mô tả</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <tr id="hiddenRow">
                        <td class="no">1</td>
                        <td style="width: 130px;">
                          <div class="ui-widget">                            
                            <select name="stores[]">
                                <option value=""></option>
                                <?php foreach($this->stores as $item):?>
                                    <option value="<?php echo $item->getId();?>"><?php echo $item->getName();?></option>
                                <?php endforeach;?>
                            </select>
                          </div>
                        </td>
                        <td style="width: 100%;"><textarea rows="3" cols="" class="description" name="description[]"></textarea></td>
                        <td style="width: 50px;"><a href="javascript:void(0)" class="delOrder" title="Xóa dòng" ><span class="icon-trash" ></span></a></td>
                    </tr>
                    <tr class="orderRow">
                        <td class="no">1</td>
                         <td style="width: 130px;"> 
                            <div class="ui-widget">                            
                                <select class="store" name="stores[]">
                                    <option value=""></option>
                                    <?php foreach($this->stores as $item):?>
                                        <option value="<?php echo $item->getId();?>"><?php echo $item->getName();?></option>
                                    <?php endforeach;?>
                                </select>
                           </div>
                        </td>
                        <td style="width: 100%;"><textarea rows="3" cols="" class="description" name="description[]"></textarea></td>
                        <td style="width: 50px; vertical-align='middle'" ><a href="javascript:void(0)" class="delOrder" title="Xóa dòng" ><span class="icon-trash"></span></a></td>
                    </tr>
                    <tr>
                        <td colspan="4" style="text-align: right"><a href="javascript:void(0)" class="btn" id="addRow" title="Thêm dòng mới"><span class="icon-plus-sign"></span></a></td>
                    </tr>
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="4"><input type="submit" name="btnSave" id="btnSave" value="Lưu" class="btn" title="Lưu yêu cầu đặt hàng"/></td>
                    </tr>
                </tfoot>
            </table>         
        </form>
        
   </div>
  <div class="span2"></div>
  <div class="span11">
        <h4>Thông tin đặt hàng</h4>
         <form action ="<?php echo $this->url('customer', array('action'=>'order'));?>" 
                name="orderForm"
                method="post" id="orderForm">
           <div id="orderList">        
<?php endif;?>
                   
            <input type="hidden" name="page" id="page" value="<?php echo $page; ?>" />            
            <table class="table">
            <thead>
               <tr>                     
                    <th style="width: 25px;">#</th> 
                    <th style="width: 80px;">Ngày</th>                   
                    <th>Store</th>                   
                    <th>Mô tả</th>
                    <th>Ghi chú</th>
                    <th style="width: 80px;">Trạng thái</th>
                    <th></th>                      
               </tr>            
            </thead>
            <tbody>
                <?php $i = ($page -1)* $row + 1 ;?>
                <?php foreach($paginator as $item):?>
               <tr>
                    <td style="text-align:center;"><?php echo $i++; ?></td>
                    <td ><?php echo date('d-m-Y',strtotime($item->getDatecreated()));?></td>
                    <td ><?php echo $item->getStore_name();?></td>
                    <td><div class="divDescription"><?php echo $item->getDescription(); ?></div></td>
                    <td ><div class="divNote"><?php echo $item->getNote();?></div></td> 
                    <td ><?php echo $item->getStatus();?></td> 
                    <td <?php echo $item->getStatus()=='waiting'?'colspan="2"':'';?> >
                       <?php if ($item->getStatus()=='waiting'):?>
                        
                       <?php endif;?>
                   </td>                
                    
               </tr>
               <?php endforeach;?>
            </tbody>
            <tfoot>
                <tr>
                            <td colspan="8">
                                 <?php    
                                    $url = $this->url('customer', array('action'=>'order'));
                                            echo $this->paginationControl(
                                                        $paginator, 'Sliding', 'paginator-slide', 
                                                        array('url'=>$url,'action'=>'order')
                                    );
                                ?>   
                            </td>
                           </tr>
            </tfoot>
            </table>
<?php if (!$this->isAjaxRequest):?>
        </div> 
       </form>
    </div>
<?php endif;?>


 
    
